apiVersion: v1
appVersion: "7.1.0.M2"
description: A Helm chart for Activiti Cloud Platform Jenkins-X CI/CD Quickstart
icon: "https://salaboy.files.wordpress.com/2018/01/acitiviti_icon_fullcolor_github_400x400.png"
name: activiti-cloud-application
version: 0.0.1-SNAPSHOT
